### ISSUE TITLE
the environment variable for HDFS is wrong

### ISSUE THREAD

**Issue by ajnavarro** [src-d/core-retrieval#31]
it is CONFIG_H_D_F_S and should be CONFIG_HDFS

**Comment by smola** [comment]
Let's fix this in `envconfig`.

**Comment by mcarmonaa** [comment]
_PRs to solve it_:
* https://github.com/src-d/core-retrieval/pull/33
* https://github.com/src-d/framework/pull/30

**Comment by ajnavarro** [comment]
fixed.
