### ISSUE TITLE
Do not panic in construct functions

### ISSUE THREAD

**Issue by jfontan** [src-d/core-retrieval#53]
Currently some construct functions panic with it's not able to connect to a service. For example:

```go
// Broker returns a queue.Broker for the default queue system.
func Broker() queue.Broker {
	if container.Broker == nil {
		b, err := queue.NewBroker(config.Broker)
		if err != nil {
			panic(err)
		}

		container.Broker = b
	}

	return container.Broker
}

// Database returns a sql.DB for the default database. If it is not possible to
// connect to the database, this function will panic. Multiple calls will always
// return the same instance.
func Database() *sql.DB {
	if container.Database == nil {
		container.Database = database.Must(database.Default())
	}

	return container.Database
}
```

If these functions can fail they should return an error so connection can be retried or a proper message shown by the program that uses it.

**Comment by erizocosmico** [comment]
That's by design. Construction should happen once on initialization and that's ok to panic because not being able to initialize something means the app should die.

**Comment by ajnavarro** [comment]
I think @jfontan wants to use these functions to try to reconnect if the connection previously fails. If we return a panic, is ok for the first case (initialization of the application), but in the case of a reconnection, is useful to have an error instead of a panic.

**Comment by erizocosmico** [comment]
Ok, for that use case it does sound good.

**Comment by jfontan** [comment]
I'm not that pushy for this change and maybe for us is OK. I've only found strange that Borges instead of retrying to connect to rabbitmq or giving a human readable error throws an stacktrace.
