### ISSUE TITLE
Add RootRepositoriesTempDir to local copier

### ISSUE THREAD

**Issue by jfontan** [src-d/core-retrieval#57]
`HSDFCopier` does not write directly into the output siva file. It instead does the copy to a temporary directory and does a rename. This is done so no siva files are corrupted in case of borges error or stop.

Do the same in `LocalCopier`.

https://github.com/src-d/core-retrieval/blob/master/repository/copier.go#L55

**Comment by rporres** [comment]
For gluster it would be much better copying to `file.siva.tmp` than copying it to a different folder, as that would imply Gluster would need [to do some magic](http://blog.vorona.ca/the-way-gluster-fs-handles-renaming-the-file.html) to avoid file being moved to a different brick

Borges makes sure that no two workers are handling at the same time the same rooted repository. It would be great to add the cleanup of `.tmp` files to avoid doing housekeeping anywhere else.

**Comment by rporres** [comment]
Most likely this should be implemented above `LocalCopier` to make sure that a new copier type will work the same way... Especially if the graceful shutdown depends on this to make sure no half copied files exist.

**Comment by ajnavarro** [comment]
Superseded by #58
