### ISSUE TITLE
Redesign Copiers so that high level logic can be reused

### ISSUE THREAD

**Issue by erizocosmico** [src-d/core-retrieval#58]
As @rporres said on https://github.com/src-d/core-retrieval/issues/57, there's some common high level logic that should be reused across all copiers. For example, copying to a .tmp file and then renaming. Instead of doing this one time, we're implementing this in each copier.

I propose redesigning the copiers to be more like building blocks that are assembled by a `Copier` that can have a `RemoteFs` (or something like that) that is the one providing client-specific logic to the copier.

Copier would be something like this, containing all the high-level logic:

```go
type Copier struct {
  remote RemoteFs
  local LocalFs
}

func (Copier) CopyToRemote(ctx context.Context, src, dst string, localFs billy.Filesystem) error {}
func (Copier) CopyFromRemote(ctx context.Context, src, dst string, localFs billy.Filesystem) error {}
```

And the `RemoteFs`/`LocalFs` (name TBD) something like this:

```go
type Fs interface {
  Open(path string) (io.Reader, error)
  WriteTo(path string) (io.Writer, error)
  Rename(src, dst string) error
}

type RemoteFs interface {
  Fs
  isRemote()
}

type LocalFs interface {
  Fs
  isLocal()
}
```

With this logic, all we need is a `io.Copy` that works with `context.Context` and the logic becomes (in pseudo-code):

```
CopyToRemote(ctx, src, dst) {
  r, err = local.Open(src)
  if err != nil { return }

  w, err = remote.WriteTo(withTmp(dst))
  if err != nil { return }

  err = copyCtx(ctx, r, w)
  if err != nil { return }

  remote.Rename(withTmp(dst), dst)
}
```

It becomes really easy to build high-level logic with very low level building blocks.

In fact, this could be simplified even further into a function, independent of remotes and locals:

```go
type Copier func(ctx context.Context, src, dst string) error

func (c Copier) Copy(ctx context.Context, src, dst string) error { return c(ctx, src, dst) }

func NewCopier(from, to Fs) Copier {
  return func(ctx context.Context, src, dst string) error {
    // code from above
  }
}
```

What do you think? /cc @src-d/data-retrieval @smola

**Comment by erizocosmico** [comment]
Yep, tmp files are kept in another directory

**Comment by ajnavarro** [comment]
By default, if you don't specify another directory for tmp files, the directory must be the same.
